# Generated by Django 5.1.7 on 2025-03-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='img')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(blank=True, choices=[('Nike', 'NIKE'), ('Hoka', 'HOKA'),
                                                                 ('Salomon', 'SALOMON'), ('Gucci', 'GUCCI'), 
                                                                ('Dybbuk', 'DYBBUK'), ('Converse', 'CONVERSE'), 
                                                                ('Jordan', 'JORDAN'), ('Vans', 'VANS')], max_length=15, null=True)),
                ('color', models.CharField(max_length=100)),
                                                                
            ],
        ),
    ]
